platform :ios, "9.0"

target 'INSElectronicProgramGuideLayout' do
  pod 'MagicalRecord' , :git => 'https://github.com/magicalpanda/MagicalRecord', :tag => 'v2.3.2'
  pod 'LoremIpsum' , :git => 'https://github.com/lukaskubanek/LoremIpsum', :tag => 'v1.0.0'
end

inhibit_all_warnings!

